<a href="https://colab.research.google.com/github/Vijayrrs485/Ruff-Stuff/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Machine Learning*** -***Linear Regression simple model Training***\

---


---

In [ ]:
import pandas as pd
df=pd.read_csv("/content/home_prices.csv")
df.head()

area_sqr_ft  price_lakhs
0          656         39.0
1         1260         83.2
2         1057         86.6
3         1259         59.0
4         1800        140.0

In [ ]:
# Model Training
from sklearn.linear_model import LinearRegression
LinearRegression().fit(df[['area_sqr_ft']],df[['price_lakhs']])

LinearRegression()

In [ ]:
# Model Prediction
model=LinearRegression().fit(df[['area_sqr_ft']],df[['price_lakhs']])
model.predict([[1500]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[95.56913434]])

In [ ]:
#m=coeff=slope, b=intercept
model.coef_, model.intercept_

(array([[0.05168176]]), array([18.0465011]))

In [ ]:
# y=mx+b ( price=m*area + b)
model.coef_[0]*1500+model.intercept_  # mathematical way(understand the concept)very easy

array([95.56913434])


***Multiple Linear Regression model training on simple dataset***


---



In [ ]:
import pandas as pd
df=pd.read_csv("home_prices.csv")
#df.sample(5)
df[["area_sqr_ft", "bedrooms"]]

area_sqr_ft  bedrooms
0           656         2
1          1260         2
2          1057         3
3          1259         2
4          1800         3
5          1325         2
6          1085         3
7          1110         2
8          1700         3
9           960         2
10         1800         3
11          700         2

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(df[["area_sqr_ft", "bedrooms"]], df[["price_lakhs"]])

LinearRegression()

In [ ]:
model.predict([[1500,3]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[106.82967328]])

In [ ]:
no_error=pd.DataFrame([{'area_sqr_ft':1500, 'bedrooms':3}])
model.predict(no_error)

array([[106.82967328]])

In [ ]:
model.coef_ #m1 and m2

array([[2.66959723e-02, 3.10399604e+01]])

In [ ]:
model.intercept_ #b

array([-26.33416621])



\***Implementation of Gradient Descent*** \

---



In [ ]:
#internal concept of .fit method (without scikit learn)


***Evalution Metrics\\***

---




In [ ]:
import pandas as pd
df = pd.read_excel("/content/mpg.xlsx")
df.head()

cylinders  displacement  horsepower  weight  acceleration  model_year  \
0          8         307.0       130.0    3504          12.0          70   
1          8         350.0       165.0    3693          11.5          70   
2          8         318.0       150.0    3436          11.0          70   
3          8         304.0       150.0    3433          12.0          70   
4          8         302.0       140.0    3449          10.5          70   

   origin                   car_name   mpg  
0       1  chevrolet chevelle malibu  18.0  
1       1          buick skylark 320  15.0  
2       1         plymouth satellite  18.0  
3       1              amc rebel sst  16.0  
4       1                ford torino  17.0

In [ ]:
df.columns = df.columns.str.strip()
X=df[['displacement', 'horsepower', 'weight', 'acceleration', 'model_year']]
y=df['mpg']
#y
X.shape, y.shape

((398, 5), (398,))

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# splitting data into training(80%) and testing data(20%)
print("Shape of X_train:", X_train.shape) #318/398=0.8
print("Shape of X_test:", X_test.shape) #80/398=0.2
print("Shape of y_train:", y_train.shape)
print("Shape of y_test:", y_test.shape)
X_test.shape

Shape of X_train: (318, 5)
Shape of X_test: (80, 5)
Shape of y_train: (318,)
Shape of y_test: (80,)


(80, 5)

In [ ]:
model=LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred=model.predict(X_test)
y_pred[:5]

array([31.5203859 , 30.72850041, 21.76539204, 16.96017243, 12.57430998])

In [ ]:
y_test[:5]

198    33.0
396    28.0
33     19.0
208    13.0
93     14.0
Name: mpg, dtype: float64

In [ ]:
from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(y_test, y_pred)

9.380062867946183

In [ ]:
r2_score(y_test, y_pred) #how much % is better

0.8255405748693174

In [ ]:
model.score(X_test, y_test)

0.8255405748693174



---



---



***Polynomial Regression(L1 & L2 Regularisation)\***

---



In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv("/content/dataset.csv")
df.head(3)

f1        f2        f3  ...      f149      f150      target
0 -0.924357 -0.326536 -1.875007  ...  0.005113 -0.234587   10.681366
1  0.001795 -1.285599 -0.726774  ...  0.058209 -1.142970  -60.163343
2  0.956702  2.319330 -0.705012  ...  0.812862  0.629629  131.226545

[3 rows x 151 columns]

In [4]:
X=df.drop(['target'], axis=1)
y=df.target
X.head(3)

f1        f2        f3  ...      f148      f149      f150
0 -0.924357 -0.326536 -1.875007  ...  0.261055  0.005113 -0.234587
1  0.001795 -1.285599 -0.726774  ...  0.153725  0.058209 -1.142970
2  0.956702  2.319330 -0.705012  ...  0.307300  0.812862  0.629629

[3 rows x 150 columns]

In [5]:
y[:3]

0     10.681366
1    -60.163343
2    131.226545
Name: target, dtype: float64

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
lm=LinearRegression()
lm.fit(X_train, y_train)
lm.score(X_test, y_test)

0.7410183335246835

In [13]:
#L1 Regularisation
lasso_model=Lasso(alpha=1.0)
lasso_model.fit(X_train, y_train)
lasso_model.score(X_test, y_test)

0.9901476660336155

In [15]:
#L2 Regularisation
ridge_model=Ridge(alpha=1.0)
ridge_model.fit(X_train, y_train)
ridge_model.score(X_test, y_test)


0.9462671341742053