<a href="https://colab.research.google.com/github/Vijayrrs485/mycode-/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("Hello World")

Hello World


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print("original array:",arr)
print("Array + 5:", arr + 5)
print("Mean:", np.mean(arr))
print("Square of elements:",np.square(arr))

original array: [1 2 3 4 5]
Array + 5: [ 6  7  8  9 10]
Mean: 3.0
Square of elements: [ 1  4  9 16 25]


In [ ]:
import numpy as n
a = n.array((1, 2, 3, 4, 5))
print(a)

[1 2 3 4 5]


In [ ]:
# Type of array

a = np.array(42)
print(a)
print(type(a))

42
<class 'numpy.ndarray'>


In [ ]:
# 2D array

a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
#check the number of dimensions

a = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(a.ndim)
print(a)

3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#accessing the elements
#slicing thw elements

a=np.array([1, 2, 3, 4])
b=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(a[2])
print(a[0]+a[3])#1+4

print(b)
print(b[0,3])

print(a[2:])
print(b[1,2:4])

3
5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
4
[3 4]
[8 9]


In [ ]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])
ar = np.array([1, 2, 3, 4])

print(arr.dtype)
print(ar.dtype)

<U6
int64


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x)
print(y)

[1 2 3 4 5]
[1 2 3 4 5]


In [ ]:
#Shaping and reshape
arr = np.array([[1, 2, 3, 4,5], [5, 6, 7, 8,9]])
print(arr.shape) #2Dimensions(rows),5elemesnts(columns)
print(arr.reshape(5,2))

(2, 5)
[[1 2]
 [3 4]
 [5 5]
 [6 7]
 [8 9]]
[1 2 3 4 5 5 6 7 8 9]
[1 2 3 4 5 5 6 7 8 9]


In [ ]:
import numpy as np
o=np.zeros([3,4])
print(o)
print(np.ones([5,6]))
print(np.random.rand(3,3))
print(np.arange(0,100,5))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0.72000329 0.66239349 0.4006992 ]
 [0.34667924 0.07232028 0.18369524]
 [0.85735519 0.73407943 0.99669062]]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
import numpy as np
a=np.zeros((2,3))
print(a)
print(np.ones((2,3)))
print(np.full((3,4),5))
print(np.eye(3)) #identity matrix
print(np.linspace(0,1,6))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
#Broadcasting
a=np.array([1,2,3])
b=np.array([3,4,5])
print(a+b)
print(a*3)
print(a*b)
print(a**b)


[4 6 8]
[3 6 9]
[ 3  8 15]
[  1  16 243]


In [ ]:
#stacking
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.concatenate([a,b]))
print(np.vstack([a, b]))       # vertical stack
print(np.hstack([a, b]))       #horizontal stack

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
#universal functions (ufuncs)
z=np.array([1,4,9])
print(np.sqrt(z))
print(np.log(z))
print(np.exp(z))
print(np.sin(z))
print(np.abs(z))


[1. 2. 3.]
[0.         1.38629436 2.19722458]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[ 0.84147098 -0.7568025   0.41211849]
[1 4 9]


In [ ]:
#Aggregation Functions
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr.sum())           # sum of all elements
print(arr.sum(axis=0))     # sum along columns
print(arr.sum(axis=1))     # sum along rows
print(arr.mean())          # average
print(arr.std())          # standard deviation
print(arr.min())
print(arr.max())
print(arr.argmin())
print(arr.argmax())  # indices of min/max

21
[5 7 9]
[ 6 15]
3.5
1.707825127659933
1
6
0
5


In [ ]:
#Linear Algebra
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print(np.dot(a, b))        # matrix multiplication
a @ b               # alternative syntax for matrix multiplication
print(np.linalg.inv(a))    # matrix inverse
print(np.linalg.det(a))   # determinant
print(np.linalg.eig(a))    # eigenvalues and eigenvectors
print(np.transpose(a))     # or a.T

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
-2.0000000000000004
EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
[[1 3]
 [2 4]]


In [ ]:
#Vectorization instead of loops
print(arr**2 + 2*arr + 1)

[[ 4  9 16]
 [25 36 49]]


In [ ]:
"""
COMPLETE NUMPY TUTORIAL - FROM ZERO TO PRO
A comprehensive program demonstrating all major NumPy concepts
"""

import numpy as np
import time

print("=" * 80)  # ================================================================================
print("NUMPY COMPLETE TUTORIAL - ALL CONCEPTS IN ONE PROGRAM")  # NUMPY COMPLETE TUTORIAL - ALL CONCEPTS IN ONE PROGRAM
print("=" * 80)  # ================================================================================

# ============================================================================
# 1. ARRAY CREATION
# ============================================================================
print("\n1. ARRAY CREATION")  # 1. ARRAY CREATION
print("-" * 40)  # ----------------------------------------

# From Python lists
arr1d = np.array([1, 2, 3, 4, 5])
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("1D Array:", arr1d)  # 1D Array: [1 2 3 4 5]
print("2D Array:\n", arr2d)  # 2D Array:
                               # [[1 2 3]
                               #  [4 5 6]
                               #  [7 8 9]]

# Built-in creation functions
zeros = np.zeros((2, 3))
ones = np.ones((2, 3))
full = np.full((2, 3), 7)
eye = np.eye(3)
arange = np.arange(0, 10, 2)
linspace = np.linspace(0, 1, 5)
random = np.random.rand(2, 3)

print("\nZeros:\n", zeros)  # Zeros:
                             # [[0. 0. 0.]
                             #  [0. 0. 0.]]
print("Ones:\n", ones)  # Ones:
                        # [[1. 1. 1.]
                        #  [1. 1. 1.]]
print("Full of 7s:\n", full)  # Full of 7s:
                               # [[7 7 7]
                               #  [7 7 7]]
print("Identity Matrix:\n", eye)  # Identity Matrix:
                                   # [[1. 0. 0.]
                                   #  [0. 1. 0.]
                                   #  [0. 0. 1.]]
print("Arange:", arange)  # Arange: [0 2 4 6 8]
print("Linspace:", linspace)  # Linspace: [0.   0.25 0.5  0.75 1.  ]
print("Random:\n", random)  # Random: (random values between 0 and 1)

# ============================================================================
# 2. ARRAY ATTRIBUTES
# ============================================================================
print("\n2. ARRAY ATTRIBUTES")  # 2. ARRAY ATTRIBUTES
print("-" * 40)  # ----------------------------------------

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print("Array:\n", arr)  # Array:
                         # [[1 2 3 4]
                         #  [5 6 7 8]]
print("Shape:", arr.shape)  # Shape: (2, 4)
print("Dimensions:", arr.ndim)  # Dimensions: 2
print("Size:", arr.size)  # Size: 8
print("Data Type:", arr.dtype)  # Data Type: int64
print("Item Size (bytes):", arr.itemsize)  # Item Size (bytes): 8
print("Total Bytes:", arr.nbytes)  # Total Bytes: 64

# ============================================================================
# 3. INDEXING AND SLICING
# ============================================================================
print("\n3. INDEXING AND SLICING")  # 3. INDEXING AND SLICING
print("-" * 40)  # ----------------------------------------

arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Original Array:", arr1d)  # Original Array: [0 1 2 3 4 5 6 7 8 9]
print("Element at index 3:", arr1d[3])  # Element at index 3: 3
print("Slice [2:7]:", arr1d[2:7])  # Slice [2:7]: [2 3 4 5 6]
print("Every 2nd element:", arr1d[::2])  # Every 2nd element: [0 2 4 6 8]
print("Reversed:", arr1d[::-1])  # Reversed: [9 8 7 6 5 4 3 2 1 0]

arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("\n2D Array:\n", arr2d)  # 2D Array:
                                # [[ 1  2  3  4]
                                #  [ 5  6  7  8]
                                #  [ 9 10 11 12]]
print("Element at [1, 2]:", arr2d[1, 2])  # Element at [1, 2]: 7
print("First 2 rows, last 2 columns:\n", arr2d[:2, 2:])  # First 2 rows, last 2 columns:
                                                          # [[3 4]
                                                          #  [7 8]]

# Boolean indexing
print("\nBoolean Indexing:")  # Boolean Indexing:
mask = arr1d > 5
print("Mask (arr > 5):", mask)  # Mask (arr > 5): [False False False False False False  True  True  True  True]
print("Elements > 5:", arr1d[mask])  # Elements > 5: [6 7 8 9]
print("Even numbers:", arr1d[arr1d % 2 == 0])  # Even numbers: [0 2 4 6 8]

# ============================================================================
# 4. ARRAY OPERATIONS
# ============================================================================
print("\n4. ARRAY OPERATIONS")  # 4. ARRAY OPERATIONS
print("-" * 40)  # ----------------------------------------

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print("a =", a)  # a = [1 2 3 4]
print("b =", b)  # b = [5 6 7 8]
print("a + b =", a + b)  # a + b = [ 6  8 10 12]
print("a - b =", a - b)  # a - b = [-4 -4 -4 -4]
print("a * b =", a * b)  # a * b = [ 5 12 21 32]
print("a / b =", a / b)  # a / b = [0.2        0.33333333 0.42857143 0.5       ]
print("a ** 2 =", a ** 2)  # a ** 2 = [ 1  4  9 16]
print("a + 10 =", a + 10)  # a + 10 = [11 12 13 14]

# ============================================================================
# 5. UNIVERSAL FUNCTIONS (ufuncs)
# ============================================================================
print("\n5. UNIVERSAL FUNCTIONS")  # 5. UNIVERSAL FUNCTIONS
print("-" * 40)  # ----------------------------------------

arr = np.array([1, 4, 9, 16, 25])
print("Array:", arr)  # Array: [ 1  4  9 16 25]
print("Square root:", np.sqrt(arr))  # Square root: [1. 2. 3. 4. 5.]
print("Exponential:", np.exp(arr[:3]))  # Exponential: [2.71828183e+00 5.45981500e+01 8.10308393e+03]
print("Natural log:", np.log(arr))  # Natural log: [0.         1.38629436 2.19722458 2.77258872 3.21887582]
print("Sine:", np.sin(arr))  # Sine: [ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]
print("Absolute value:", np.abs(np.array([-1, -2, 3, -4])))  # Absolute value: [1 2 3 4]

# ============================================================================
# 6. RESHAPING
# ============================================================================
print("\n6. RESHAPING")  # 6. RESHAPING
print("-" * 40)  # ----------------------------------------

arr = np.arange(12)
print("Original (1D):", arr)  # Original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped = arr.reshape(3, 4)
print("Reshaped to (3, 4):\n", reshaped)  # Reshaped to (3, 4):
                                           # [[ 0  1  2  3]
                                           #  [ 4  5  6  7]
                                           #  [ 8  9 10 11]]
reshaped3d = arr.reshape(2, 2, 3)
print("Reshaped to (2, 2, 3):\n", reshaped3d)  # Reshaped to (2, 2, 3):
                                                # [[[ 0  1  2]
                                                #   [ 3  4  5]]
                                                #  [[ 6  7  8]
                                                #   [ 9 10 11]]]
print("Flattened:", reshaped.flatten())  # Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
print("Transposed:\n", reshaped.T)  # Transposed:
                                     # [[ 0  4  8]
                                     #  [ 1  5  9]
                                     #  [ 2  6 10]
                                     #  [ 3  7 11]]

# ============================================================================
# 7. STACKING AND SPLITTING
# ============================================================================
print("\n7. STACKING AND SPLITTING")  # 7. STACKING AND SPLITTING
print("-" * 40)  # ----------------------------------------

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("a =", a)  # a = [1 2 3]
print("b =", b)  # b = [4 5 6]
print("Vertical stack:\n", np.vstack([a, b]))  # Vertical stack:
                                                # [[1 2 3]
                                                #  [4 5 6]]
print("Horizontal stack:", np.hstack([a, b]))  # Horizontal stack: [1 2 3 4 5 6]
print("Concatenate:", np.concatenate([a, b]))  # Concatenate: [1 2 3 4 5 6]

arr = np.arange(9)
print("\nArray to split:", arr)  # Array to split: [0 1 2 3 4 5 6 7 8]
print("Split into 3 parts:", np.split(arr, 3))  # Split into 3 parts: [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]

# ============================================================================
# 8. AGGREGATION FUNCTIONS
# ============================================================================
print("\n8. AGGREGATION FUNCTIONS")  # 8. AGGREGATION FUNCTIONS
print("-" * 40)  # ----------------------------------------

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr)  # Array:
                         # [[1 2 3]
                         #  [4 5 6]
                         #  [7 8 9]]
print("Sum of all elements:", arr.sum())  # Sum of all elements: 45
print("Sum along axis 0 (columns):", arr.sum(axis=0))  # Sum along axis 0 (columns): [12 15 18]
print("Sum along axis 1 (rows):", arr.sum(axis=1))  # Sum along axis 1 (rows): [ 6 15 24]
print("Mean:", arr.mean())  # Mean: 5.0
print("Standard deviation:", arr.std())  # Standard deviation: 2.581988897471611
print("Min:", arr.min(), "Max:", arr.max())  # Min: 1 Max: 9
print("Index of min:", arr.argmin(), "Index of max:", arr.argmax())  # Index of min: 0 Index of max: 8
print("Median:", np.median(arr))  # Median: 5.0
print("Cumulative sum:", np.cumsum(arr))  # Cumulative sum: [ 1  3  6 10 15 21 28 36 45]

# ============================================================================
# 9. BROADCASTING
# ============================================================================
print("\n9. BROADCASTING")  # 9. BROADCASTING
print("-" * 40)  # ----------------------------------------

a = np.array([[1], [2], [3]])  # shape (3, 1)
b = np.array([10, 20, 30])     # shape (3,)

print("a (3x1):\n", a)  # a (3x1):
                         # [[1]
                         #  [2]
                         #  [3]]
print("b (3,):", b)  # b (3,): [10 20 30]
print("a + b (broadcasting):\n", a + b)  # a + b (broadcasting):
                                          # [[11 21 31]
                                          #  [12 22 32]
                                          #  [13 23 33]]

# Practical example: normalize each row
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_means = matrix.mean(axis=1, keepdims=True)
normalized = matrix - row_means
print("\nOriginal matrix:\n", matrix)  # Original matrix:
                                        # [[1 2 3]
                                        #  [4 5 6]
                                        #  [7 8 9]]
print("Row means:\n", row_means)  # Row means:
                                   # [[2.]
                                   #  [5.]
                                   #  [8.]]
print("Normalized (subtract row mean):\n", normalized)  # Normalized (subtract row mean):
                                                        # [[-1.  0.  1.]
                                                        #  [-1.  0.  1.]
                                                        #  [-1.  0.  1.]]

# ============================================================================
# 10. LINEAR ALGEBRA
# ============================================================================
print("\n10. LINEAR ALGEBRA")  # 10. LINEAR ALGEBRA
print("-" * 40)  # ----------------------------------------

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", a)  # Matrix A:
                          # [[1 2]
                          #  [3 4]]
print("Matrix B:\n", b)  # Matrix B:
                          # [[5 6]
                          #  [7 8]]
print("Matrix multiplication (A @ B):\n", a @ b)  # Matrix multiplication (A @ B):
                                                   # [[19 22]
                                                   #  [43 50]]
print("Transpose of A:\n", a.T)  # Transpose of A:
                                  # [[1 3]
                                  #  [2 4]]
print("Determinant of A:", np.linalg.det(a))  # Determinant of A: -2.0000000000000004
print("Inverse of A:\n", np.linalg.inv(a))  # Inverse of A:
                                             # [[-2.   1. ]
                                             #  [ 1.5 -0.5]]

eigenvalues, eigenvectors = np.linalg.eig(a)
print("Eigenvalues:", eigenvalues)  # Eigenvalues: [-0.37228132  5.37228132]
print("Eigenvectors:\n", eigenvectors)  # Eigenvectors:
                                        # [[-0.82456484 -0.41597356]
                                        #  [ 0.56576746 -0.90937671]]

# ============================================================================
# 11. FANCY INDEXING
# ============================================================================
print("\n11. FANCY INDEXING")  # 11. FANCY INDEXING
print("-" * 40)  # ----------------------------------------

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array:\n", arr)  # Array:
                         # [[1 2 3]
                         #  [4 5 6]
                         #  [7 8 9]]

rows = np.array([0, 2])
cols = np.array([1, 2])
print("Fancy indexing [rows=[0,2], cols=[1,2]]:", arr[rows, cols])  # Fancy indexing [rows=[0,2], cols=[1,2]]: [2 9]

indices = [0, 2, 1]
print("Reorder rows [0, 2, 1]:\n", arr[indices])  # Reorder rows [0, 2, 1]:
                                                   # [[1 2 3]
                                                   #  [7 8 9]
                                                   #  [4 5 6]]

# ============================================================================
# 12. RANDOM NUMBERS
# ============================================================================
print("\n12. RANDOM NUMBERS")  # 12. RANDOM NUMBERS
print("-" * 40)  # ----------------------------------------

np.random.seed(42)  # For reproducibility
print("Random float [0, 1):", np.random.rand(3))  # Random float [0, 1): [0.37454012 0.95071431 0.73199394]
print("Random normal distribution:", np.random.randn(3))  # Random normal distribution: [-0.30230275 -1.04855297 -1.42001794]
print("Random integers [0, 10):", np.random.randint(0, 10, 5))  # Random integers [0, 10): [1 3 6 7 8]
print("Random choice from list:", np.random.choice([1, 2, 3, 4], size=5))  # Random choice from list: [4 4 1 1 4]

# ============================================================================
# 13. VIEWS VS COPIES
# ============================================================================
print("\n13. VIEWS VS COPIES")  # 13. VIEWS VS COPIES
print("-" * 40)  # ----------------------------------------

original = np.array([1, 2, 3, 4, 5])
print("Original:", original)  # Original: [1 2 3 4 5]

# View (shares memory)
view = original[1:4]
view[0] = 99
print("After modifying view, original:", original)  # After modifying view, original: [ 1 99  3  4  5]

# Copy (independent)
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()
copy[0] = 77
print("After modifying copy, original:", original)  # After modifying copy, original: [1 2 3 4 5]

# ============================================================================
# 14. CONDITIONAL OPERATIONS
# ============================================================================
print("\n14. CONDITIONAL OPERATIONS")  # 14. CONDITIONAL OPERATIONS
print("-" * 40)  # ----------------------------------------

arr = np.arange(10)
print("Array:", arr)  # Array: [0 1 2 3 4 5 6 7 8 9]

# np.where: vectorized if-else
result = np.where(arr > 5, arr * 2, arr / 2)
print("If > 5: multiply by 2, else divide by 2:", result)  # If > 5: multiply by 2, else divide by 2: [ 0.   0.5  1.   1.5  2.   2.5 12.  14.  16.  18. ]

# np.clip: limit values
clipped = np.clip(arr, 2, 7)
print("Clip values to [2, 7]:", clipped)  # Clip values to [2, 7]: [2 2 2 3 4 5 6 7 7 7]

# ============================================================================
# 15. ADVANCED: EINSTEIN SUMMATION
# ============================================================================
print("\n15. EINSTEIN SUMMATION (einsum)")  # 15. EINSTEIN SUMMATION (einsum)
print("-" * 40)  # ----------------------------------------

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("Matrix A:\n", a)  # Matrix A:
                          # [[1 2]
                          #  [3 4]]
print("Matrix B:\n", b)  # Matrix B:
                          # [[5 6]
                          #  [7 8]]
print("Matrix mult (einsum):\n", np.einsum('ij,jk->ik', a, b))  # Matrix mult (einsum):
                                                                 # [[19 22]
                                                                 #  [43 50]]
print("Trace (diagonal sum):", np.einsum('ii->', a))  # Trace (diagonal sum): 5
print("Transpose:\n", np.einsum('ij->ji', a))  # Transpose:
                                                # [[1 3]
                                                #  [2 4]]

# ============================================================================
# 16. PERFORMANCE: VECTORIZATION
# ============================================================================
print("\n16. VECTORIZATION PERFORMANCE")  # 16. VECTORIZATION PERFORMANCE
print("-" * 40)  # ----------------------------------------

size = 1000000
arr = np.arange(size)

# Python loop (slow)
start = time.time()
result = []
for i in range(len(arr[:10000])):  # Using smaller size for demo
    result.append(arr[i] ** 2)
loop_time = time.time() - start

# NumPy vectorized (fast)
start = time.time()
result = arr ** 2
vectorized_time = time.time() - start

print(f"Loop time (10k elements): {loop_time:.6f} seconds")  # Loop time (10k elements): ~0.002000 seconds
print(f"Vectorized time (1M elements): {vectorized_time:.6f} seconds")  # Vectorized time (1M elements): ~0.001000 seconds
print(f"Speedup: ~{loop_time / vectorized_time:.0f}x faster")  # Speedup: ~2x faster (varies by machine)

# ============================================================================
# 17. PRACTICAL EXAMPLE: DATA ANALYSIS
# ============================================================================
print("\n17. PRACTICAL EXAMPLE: STUDENT GRADES ANALYSIS")  # 17. PRACTICAL EXAMPLE: STUDENT GRADES ANALYSIS
print("-" * 40)  # ----------------------------------------

# Simulate student grades: 5 students, 3 subjects
np.random.seed(42)
grades = np.random.randint(60, 100, (5, 3))
students = ['Alice', 'Bob', 'Charlie', 'David', 'Eve']
subjects = ['Math', 'Physics', 'Chemistry']

print("Grades (rows=students, cols=subjects):\n", grades)  # Grades (rows=students, cols=subjects):
                                                            # [[74 92 92]
                                                            #  [86 68 94]
                                                            #  [75 89 93]
                                                            #  [88 79 73]
                                                            #  [72 64 67]]

# Statistics
print("\nPer-student averages:", grades.mean(axis=1))  # Per-student averages: [86.         82.66666667 85.66666667 80.         67.66666667]
print("Per-subject averages:", grades.mean(axis=0))  # Per-subject averages: [79.  78.4 83.8]
print("Overall average:", grades.mean())  # Overall average: 80.4
print("Highest grade:", grades.max())  # Highest grade: 94
print("Student with highest avg:", students[grades.mean(axis=1).argmax()])  # Student with highest avg: Alice

# Pass/Fail (>= 70 is pass)
pass_fail = np.where(grades >= 70, 'Pass', 'Fail')
print("\nPass/Fail:\n", pass_fail)  # Pass/Fail:
                                    # [['Pass' 'Pass' 'Pass']
                                    #  ['Pass' 'Fail' 'Pass']
                                    #  ['Pass' 'Pass' 'Pass']
                                    #  ['Pass' 'Pass' 'Pass']
                                    #  ['Pass' 'Fail' 'Fail']]

# Normalize grades to 0-1 scale
normalized = (grades - grades.min()) / (grades.max() - grades.min())
print("\nNormalized grades:\n", normalized)  # Normalized grades:
                                              # [[0.33333333 0.93333333 0.93333333]
                                              #  [0.73333333 0.13333333 1.        ]
                                              #  [0.36666667 0.83333333 0.96666667]
                                              #  [0.8        0.5        0.3       ]
                                              #  [0.26666667 0.         0.1       ]]

# ============================================================================
# 18. SAVING AND LOADING
# ============================================================================
print("\n18. SAVING AND LOADING ARRAYS")  # 18. SAVING AND LOADING ARRAYS
print("-" * 40)  # ----------------------------------------

arr = np.array([[1, 2, 3], [4, 5, 6]])
np.save('my_array.npy', arr)
loaded = np.load('my_array.npy')
print("Saved and loaded array:\n", loaded)  # Saved and loaded array:
                                             # [[1 2 3]
                                             #  [4 5 6]]

# Save multiple arrays
np.savez('multiple_arrays.npz', a=arr, b=grades)
data = np.load('multiple_arrays.npz')
print("Loaded 'a' from .npz:\n", data['a'])  # Loaded 'a' from .npz:
                                              # [[1 2 3]
                                              #  [4 5 6]]

print("\n" + "=" * 80)  # ================================================================================
print("TUTORIAL COMPLETE! You've seen all major NumPy concepts.")  # TUTORIAL COMPLETE! You've seen all major NumPy concepts.
print("=" * 80)  # ================================================================================

NUMPY COMPLETE TUTORIAL - ALL CONCEPTS IN ONE PROGRAM

1. ARRAY CREATION
----------------------------------------
1D Array: [1 2 3 4 5]
2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]
Full of 7s:
 [[7 7 7]
 [7 7 7]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Arange: [0 2 4 6 8]
Linspace: [0.   0.25 0.5  0.75 1.  ]
Random:
 [[0.37261602 0.0937223  0.46095703]
 [0.32559859 0.25157029 0.32373681]]

2. ARRAY ATTRIBUTES
----------------------------------------
Array:
 [[1 2 3 4]
 [5 6 7 8]]
Shape: (2, 4)
Dimensions: 2
Size: 8
Data Type: int64
Item Size (bytes): 8
Total Bytes: 64

3. INDEXING AND SLICING
----------------------------------------
Original Array: [0 1 2 3 4 5 6 7 8 9]
Element at index 3: 3
Slice [2:7]: [2 3 4 5 6]
Every 2nd element: [0 2 4 6 8]
Reversed: [9 8 7 6 5 4 3 2 1 0]

2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element at [1, 2]: 7
First 2 rows, last 2 columns:
 [[3 4]
 [7 8]]

Boolean In